name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Plugins go brrr
          base: repositories, header, activity
          config_timezone: America/New_York

          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: "Jupyter Notebook"
          plugin_languages_details: bytes-size, percentage

          plugin_lines: yes
